apiVersion: v2
name: price
description: A helm chart for real-time and historical BTC price data
type: application
version: 0.5.10
appVersion: 0.2.1

dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 14.3.1
    condition: postgresql.enabled

