# Default values for price.
replicaCount: 1
image:
  repository: us.gcr.io/galoy-org/price
  digest: "sha256:f69ce5cd409254e5d37be1e5fc0d957545333d57bf7892a084cb6f3d6934bbea"
  git_ref: "705dd6a"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 1000
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
realtime:
  config:
    - code: "USD"
      symbol: "$"
      name: "US Dollar"
      flag: "ðŸ‡ºðŸ‡¸"
    - code: "EUR"
      symbol: "â‚¬"
      name: "Euro"
      flag: "ðŸ‡ªðŸ‡º"
    - code: "GBP"
      symbol: "Â£"
      name: "British Pound"
      flag: "ðŸ‡¬ðŸ‡§"
    - code: "XCD"
      symbol: "$"
      name: "East Caribbean Dollar"
      flag: "ðŸ‡¦ðŸ‡¬"
    - code: "ANG"
      symbol: "Æ’"
      name: "Netherlands Antillean Guilder"
      flag: "ðŸ‡¨ðŸ‡¼"
    - code: "HTG"
      symbol: "G"
      name: "Haitian Gourde"
      flag: "ðŸ‡­ðŸ‡¹"
    - code: "BSD"
      symbol: "$"
      name: "Bahamian Dollar"
      flag: "ðŸ‡§ðŸ‡¸"
    - code: "BBD"
      symbol: "$"
      name: "Barbadian Dollar"
      flag: "ðŸ‡§ðŸ‡§"
    - code: "BZD"
      symbol: "BZ$"
      name: "Belize Dollar"
      flag: "ðŸ‡§ðŸ‡¿"
    - code: "KYD"
      symbol: "$"
      name: "Cayman Islands Dollar"
      flag: "ðŸ‡°ðŸ‡¾"
    - code: "CUP"
      symbol: "$"
      name: "Cuban Peso"
      flag: "ðŸ‡¨ðŸ‡º"
    - code: "DOP"
      symbol: "RD$"
      name: "Dominican Peso"
      flag: "ðŸ‡©ðŸ‡´"
    - code: "XCD"
      symbol: "$"
      name: "East Caribbean Dollar"
      flag: "ðŸ‡¬ðŸ‡©"
    - code: "HTG"
      symbol: "G"
      name: "Haitian Gourde"
      flag: "ðŸ‡­ðŸ‡¹"
    - code: "JMD"
      symbol: "J$"
      name: "Jamaican Dollar"
      flag: "ðŸ‡¯ðŸ‡²"
    - code: "TTD"
      symbol: "TT$"
      name: "Trinidad and Tobago Dollar"
      flag: "ðŸ‡¹ðŸ‡¹"
  image:
    repository: us.gcr.io/galoy-org/price
    digest: "sha256:6e0fb096efb7ef5aa80e7dd8e9ffa3a97a5d3185d714f7a39d3ffc3c740e8a99"
    git_ref: "82341ad"
  service:
    type: ClusterIP
    prometheus: 9464
    grpc: 50051
  podAnnotations:
    prometheus.io/path: /metrics
    prometheus.io/port: "9464"
    prometheus.io/scrape: "true"
history:
  valuesOverride: {}
  image:
    repository: us.gcr.io/galoy-org/price-history
    digest: "sha256:14ba8a6ab92f5c5c7d7682bbf93d0db5a3ad980b29c53432d4b888d223c25f3a"
  service:
    type: ClusterIP
    prometheus: 9464
    grpc: 50052
  migrateImage:
    repository: us.gcr.io/galoy-org/price-history-migrate
    digest: sha256:84c48c442ac15903f8ed3ff373ea0cccb64fe6a1d48d3fc456780217fccf85ae
  cron:
    resources: {}
  migrationJob:
    resources: {}

postgresql:
  enabled: true
  nameOverride: price-history-db
  primary:
    persistence:
      enabled: true
      storageClass: do-block-storage-xfs-retain # xfs is file system format
      size: 8Gi # Default. Current size is 7756 kB. Find out why 
  auth:
    enablePostgresUser: false
    username: price-history
    database: price-history
    password: price-history
