{{- if and .Values.vector.enabled .Values.vector.sinks.honeycomb.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "strfry.fullname" . }}-honeycomb
type: Opaque
data:
  apiKey: {{ .Values.vector.sinks.honeycomb.apiKey | b64enc | quote }}
{{- end }}
